# Generated by Django 3.2.3 on 2021-05-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='star_rating_average',
            field=models.FloatField(default=5),
        ),
    ]
